### ISSUE TITLE
Crashes on Win10

### ISSUE THREAD

**Issue by mlugo-apx** [brian112358/avermore-miner#1]
Just downloaded, added exception to Windows Defender.  Edited the start batch file.  Immediately crashes after launching.  Log attached, the file doesn't include anything that stands out.

[suprnova_log.txt](https://github.com/brian112358/avermore-miner/files/1908283/suprnova_log.txt)

**Comment by mlugo-apx** [comment]
Fixed, the Example.bat file has this:

set GPU_FORCE_64BIT_PTR=1

Setting it to 0:

set GPU_FORCE_64BIT_PTR=0

Fixed the issue, now up and running.  Going to have to tweak because I am getting KH instead of MH.

**Comment by brian112358** [comment]
Awesome! Glad to hear it's working now. I'll add the fix to the [Troubleshooting](https://github.com/brian112358/avermore-miner/wiki/Troubleshooting) page.
